print('===============')
print('DESAFIO 001')
print('================')
nome = input('Qual o seu nome na Armada? ')
print('=======================')
print('SEJA- MUITO BEM VINDO ')
print('A ARMADA DOS CODERS')
print('É um prazer te conhecer, {}!'.format((nome)))
print('======================')
